[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
solanatoken = "7MCEfe5NNGmfv2TiGDthDPF5T4TrsWFLRHAA5WMC7sTo"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
